# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-03 10:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('neibor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='profiles/'),
            preserve_default=False,
        ),
    ]
